- defaults:
    link:
      relink: true
      create: true
    create:
      mode: 0755

- clean: ["~", "~/.config"]

- link:
    ~/.local/bin:
      path: bin

    ~/.shell_local_before:
      path: shell/shell_local_before

    ~/.shell_local_after:
      path: shell/shell_local_after

    ~/.zshrc_local_before:
      path: zsh/zshrc_local_before

    ~/.zshrc_local_after:
      path: zsh/zshrc_local_after

    ~/.bashrc_local_before:
      path: bash/bashrc_local_before

    ~/.bashrc_local_after:
      path: bash/bashrc_local_after

    ~/.config/aerospace:
      path: aerospace

    ~/.config/hammerspoon:
      path: hammerspoon

    ~/.hammerspoon:
      path: ~/.config/hammerspoon
- create:
    - ~/work
    - ~/study
    - ~/personal
    - ~/archive
    - ~/misc
    - ~/templates

- shell:
    - git submodule update --init --recursive
