- defaults:
    link:
      relink: true
      create: true

- clean: ["~", "~/.config"]

- link:
    ~/.local/bin:
      path: bin

    ~/.zshrc_local_before:
      path: zsh/zshrc_local_before

    ~/.zshrc_local_after:
      path: zsh/zshrc_local_after
- shell:
    - git submodule update --init --recursive
