#!/usr/bin/env bash

set -e

# Prevent the system from sleeping while the script is running
caffeinate -s -u -w $$ &

source prerequisites/install-required.sh

CONFIG=".install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

ansible-playbook install.yaml --ask-become-pass --vault-id=./vault/vault-from-op.sh
