#!/usr/bin/env bash

set -e

source prerequisites/install-required.sh

CONFIG=".install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

ansible-playbook install.yaml --tags "1password"
ansible-playbook install.yaml --tags "ssh" --vault-id=./vault/vault-from-op.sh
ansible-playbook install.yaml --skip-tags "1password,ssh"
