- name: Install 1Password Desktop
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: 1password

- name: Install 1Password CLI
  homebrew:
    name: 1password-cli

- name: Turn on the 1Password desktop app integration (https://developer.1password.com/docs/cli/get-started/#step-2-turn-on-the-1password-desktop-app-integration)
  pause:
