- name: Check if Docker is already installed
  shell: test -d /Applications/Docker.app
  failed_when: false
  register: docker_installed

- name: Install Docker
  when: docker_installed.rc != 0
  shell: |
    cd /tmp
    curl -LO https://desktop.docker.com/mac/main/arm64/178610/Docker.dmg?_gl=1*1i4pzdy*_ga*MTY5MTYyOTI1NC4xNzM2MDI5NjY0*_ga_XJWPQMJYHQ*MTczNjAyOTY2NC4xLjEuMTczNjAzMDU0Mi45LjAuMA..
    sudo hdiutil attach Docker.dmg
    sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
    sudo hdiutil detach /Volumes/Docker
    rm -rf Docker.dmg
