- name: Install tmux
  homebrew:
    name: tmux

- name: Install fzf
  homebrew:
    name: fzf

- name: Install jq
  homebrew:
    name: jq

- name: Install tldr
  homebrew:
    name: tlrc

- name: Install shellcheck
  homebrew:
    name: shellcheck

- name: Install pup
  homebrew:
    name: pup

- name: Install lnav
  homebrew:
    name: lnav

- name: Install htop
  homebrew:
    name: htop

- name: Install tgpt
  shell: curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin
  become: true
  args:
    creates: /usr/local/bin/tgpt
