- name: Change setup-computer remote (becuase it is already cloned)
  shell: git remote set-url origin git@github.com:leorodriguesf/setup-computer.git
  args:
    chdir: ~/personal/projects/setup-computer
