- name: Install VSCode
  homebrew_cask:
    name: visual-studio-code

- name: Link settings
  file:
    src: "{{xdg_config_home}}/vscode/settings.json"
    dest: ~/Library/Application Support/Code/User/settings.json
    state: link
    force: true

- name: Link keybindings
  file:
    src: "{{xdg_config_home}}/vscode/keybindings.json"
    dest: ~/Library/Application Support/Code/User/keybindings.json
    state: link
    force: true

- name: Install extensions
  shell: cat {{xdg_config_home}}/vscode/extensions.json | jq '.[] | .identifier.id' | xargs -n1 code --install-extension
