- name: Add zsh-autosuggestions repository
  become: true
  shell: |
    echo 'deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-autosuggestions/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/shells:zsh-users:zsh-autosuggestions.list
    wget -qO- https://build.opensuse.org/projects/shells:zsh-users:zsh-autosuggestions/signing_keys/download\?kind\=gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/shells_zsh-users_zsh-autosuggestions.gpg
    sudo apt update
  args:
    creates: /etc/apt/trusted.gpg.d/shells_zsh-users_zsh-autosuggestions.gpg

- name: Add zsh-autosuggestions
  become: true
  apt:
    name: zsh-autosuggestions

- name: Install MesloLG (Nerd Font)
  shell: |
    cd /tmp
    curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.zip
    unzip Meslo.zip -d Meslo
    cp Meslo/*.ttf ~/.local/share/fonts
    rm -rf Meslo.zip Mesl
  args:
    creates: ~/.local/share/fonts/Meslo*

- name: Install starship (zsh prompt)
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship

- name: Get whoami to change its default shell
  shell: whoami
  register: user

- name: Change default shell
  become: true
  shell: sudo chsh -s /bin/zsh {{user.stdout}}